/**
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┐
 * https://trailhead.salesforce.com/en/content/learn/modules/apex_database/apex_database_intro?trail_id=force_com_dev_beginner
 *
 * This class contains a method that returns an array of formatted strings.
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @author         Emalee Soddy   <hello@emaleesoddy.com>
 * @version        1.0
 * @created        7/17/2021
 * @modified       7/17/2021
 * @systemLayer    Invocation | Service | Utility | Selector | Domain | Test
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @changes
 * v1.0            hello@emaleesoddy.com
 * 7/17/2021       Initial creation of the class.
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/

public with sharing class StringArrayTest {

}